# config file for data extraction from different IoT projects:
projects: [
data/projects/gnucobol,
data/projects/contiki,
data/projects/linux-rpi,
data/projects/ARMmbed,
data/projects/FreeRTOS,
data/projects/micropython, 
data/projects/openwrt,
data/projects/RIOT,
data/projects/tinyos, 
data/projects/mosquitto,
data/projects/mbed-os,
]
save:
  database: data/IoTvulCode.db
  override: True
  # override the existing files3
  threshold_lines: 5
  benign_ratio: 0.25
  seed: 41
  drop_dup: True
  refine_on_every: 3000
  # apply filtering after scanning the number of files
  apply_guesslang: False
  # do you want to use guess lang to classify files or use extension?
